name: Twitter Quote Bot

on:
  schedule:
    - cron: "0 */3 * * *"  # every 3 hours
  workflow_dispatch:  # lets you run it manually too

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: Get the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install tweepy pillow requests

    - name: Run the bot
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      run: python bot.py
